M48
; DRILL file {KiCad (6.0.4)} date Fri Jun  2 21:13:11 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-02T21:13:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.7539Y-2.7697
X2.7539Y-5.1319
X5.9035Y-2.7697
X5.9035Y-5.1319
T0
M30
